version: '3.7'
services:
  scrapy:
    build: ./app
    command: scrapy crawl estates
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - db
  flask:
    build: ./app
    command: python manage.py
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=scraper
      - POSTGRES_PASSWORD=scraper1234
      - POSTGRES_DB=estates

volumes:
  postgres_data: